name: Load Config Action

description: Reads a YAML config file and outputs its contents.

inputs:
  config_file:
    description: 'Path to the YAML configuration file'
    required: true

outputs:
  github_output:
    description: 'The output to be used by subsequent steps'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
        yq --version
      shell: bash

    - name: Parse YAML
      # id: read_yaml
      shell: bash
      run: |
        for key in $(yq e 'keys | .[]' "${{ inputs.config_file }}"); do
          val=$(yq e -o=json ".$key" "${{ inputs.config_file }}" | jq -c .)
          echo "$key=$val" >> "$GITHUB_OUTPUT"
        done

    # - name: Show Output
    #   run: |
    #     # GitHub Actionsの出力を表示
    #     echo "Outputs1111:"
    #     echo "jdk: ${{ steps.read_yaml.outputs.jdk }}"
    #     echo "slack_teamDomain: ${{ steps.read_yaml.outputs.slack_teamDomain }}"  # アンダースコア形式で表示
    #     echo "slack_webhookUrl: ${{ steps.read_yaml.outputs.slack_webhookUrl }}"  # アンダースコア形式で表示
    #     echo "parameter_store: ${{ steps.read_yaml.outputs.parameter_store }}"  # test1 オブジェクト全体を表示
    #     echo "secret_manager: ${{ steps.read_yaml.outputs.secret_manager }}"  # test1 オブジェクト全体を表示
    #   shell: bash