name: Load Config Action

description: Reads a YAML config file and outputs its contents.

inputs:
  config_file:
    description: 'Path to the YAML configuration file'
    required: true

outputs:
  github_output:
    description: 'The output to be used by subsequent steps'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
        yq --version
      shell: bash

    - name: Parse YAML
      id: read_yaml
      shell: bash
      run: |
        for key in $(yq e 'keys | .[]' "${{ inputs.config_file }}"); do
          val=$(yq e -o=json ".$key" "${{ inputs.config_file }}" | jq -c .)
          echo "$key=$val" >> $GITHUB_OUTPUT
        done

    # - name: Parse YAML top-level keys to outputs
    #   id: read_yaml
    #   shell: bash
    #   run: |
    #     CONFIG_FILE="${{ inputs.config_file }}"

    #     flatten() {
    #       local prefix=$1
    #       local path=$2
    #       local keys=$(yq e "$path | keys" "$CONFIG_FILE" | sed 's/- //g')

    #       for key in $keys; do
    #         local full_key="${prefix}${key}"
    #         local sub_path="${path}.${key}"
    #         local type=$(yq e "type($sub_path)" "$CONFIG_FILE")

    #         if [ "$type" = "!!map" ]; then
    #           flatten "${full_key}__" "$sub_path"
    #         else
    #           local val=$(yq e "$sub_path" "$CONFIG_FILE")
    #           echo "${full_key}=${val}" >> "$GITHUB_OUTPUT"
    #         fi
    #       done
    #     }

    #     flatten "" "."

    # - name: Read YAML file and set outputs for each field
    #   id: read_yaml
    #   run: |
    #     CONFIG_FILE="${{ inputs.config_file }}"

    #     # keysをJSON形式で取得してjqで配列展開
    #     keys=$(yq e -o=json 'keys' "$CONFIG_FILE")

    #     for key in $(echo "$keys" | jq -r '.[]'); do
    #       value=$(yq e ".$key" "$CONFIG_FILE")
          
    #       # JSONか判定するためにvalueをJSONで取得
    #       value_json=$(yq e -o=json ".$key" "$CONFIG_FILE")

    #       if [[ $(echo "$value_json" | jq 'type') == '"object"' ]]; then
    #         subkeys=$(echo "$value_json" | jq -r 'keys | .[]')
    #         for subkey in $subkeys; do
    #           subvalue=$(echo "$value_json" | jq -r ".$subkey")
    #           output_name="${key}_${subkey}"
    #           echo "${output_name}=${subvalue}" >> $GITHUB_OUTPUT
    #         done
    #         echo "${key}=$(echo "$value_json" | jq -c '.')" >> $GITHUB_OUTPUT
    #       else
    #         echo "${key}=${value}" >> $GITHUB_OUTPUT
    #       fi
    #     done
    #   shell: bash

    - name: Show Output
      run: |
        # GitHub Actionsの出力を表示
        echo "Outputs1111:"
        echo "jdk: ${{ steps.read_yaml.outputs.jdk }}"
        echo "slack_teamDomain: ${{ steps.read_yaml.outputs.slack_teamDomain }}"  # アンダースコア形式で表示
        echo "slack_webhookUrl: ${{ steps.read_yaml.outputs.slack_webhookUrl }}"  # アンダースコア形式で表示
        echo "parameter_store: ${{ steps.read_yaml.outputs.parameter_store }}"  # test1 オブジェクト全体を表示
        echo "secret_manager: ${{ steps.read_yaml.outputs.secret_manager }}"  # test1 オブジェクト全体を表示
      shell: bash