name: Get AWS AWS SSM values

description: Gets secrets from AWS Parameter Store

inputs:
  parameter_store_json:
    description: 'JSON string of { "key": "parameterName" }'
    required: true

outputs:
  github_output:
    description: 'All secrets as a JSON string'
    value: ${{ steps.fetch.outputs.github_output }}

runs:
  using: 'composite'
  steps:
    - name: Debug input
      shell: bash
      run: |
        echo "Received parameter_store_json:"
        echo '${{ inputs.parameter_store_json }}' | jq .

    - name: Fetch parameters from AWS SSM
      id: fetch
      shell: bash
      run: |
        json_output=""
        sep=""

        while IFS='=' read -r key param_name; do
          echo "Fetching: key=$key from SSM name=$param_name"
          
          # secret_value=$(aws ssm get-parameter \
          #   --name "$param_name" \
          #   --with-decryption \
          #   --query 'Parameter.Value' \
          #   --output text)
          secret_value = "testxxxx"
          json_output+="${sep}\"$key\":\"$secret_value\""
          sep=','
        done < <(echo "${{ inputs.parameter_store_json }}" | jq -r 'to_entries[] | "\(.key)=\(.value)"')

        final_json="{${json_output}}"
        echo "github_output=$final_json" >> "$GITHUB_OUTPUT"
