name: Get AWS SSM values

description: Gets secrets from AWS Parameter Store

inputs:
  input_json:
    description: 'JSON string of { "key": "parameterName" }'
    required: true

outputs:
  github_output:
    description: 'All secrets value as a JSON string'
    value: ${{ steps.fetch.outputs.github_output }}

runs:
  using: 'composite'
  steps:
    - name: Fetch value from AWS SSM
      id: fetch
      shell: bash
      run: |
        set -euo pipefail

        json_output=""
        sep=""
        PARAM_JSON='${{ inputs.input_json }}'

        while IFS='=' read -r key param_name; do          
          secret_value=$(aws ssm get-parameter \
            --name "$param_name" \
            --with-decryption \
            --query 'Parameter.Value' \
            --output text)
          json_output+="${sep}\"$key\":\"$secret_value\""
          sep=','
        done < <(echo "$PARAM_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"')

        final_json="{${json_output}}"
        echo "github_output=$final_json" >> "$GITHUB_OUTPUT"
